### ISSUE TITLE
getting error while training wnet_bright, please guide.

### ISSUE THREAD

**Issue by ZubairKhan001** [lwchen6309/unsupervised-image-segmentation-by-WNet-with-NormalizedCut#4]
File "D:\deep learning codes\unsupervised-image-segmentation-by-WNet-with-NormalizedCut\src\soft_ncut.py", line 456, in convert_to_batchTensor
new_indeces = tf.concat([tile_batch,tile_indeces],axis=1)

NameError: name 'tile_indeces' is not defined

**Comment by lwchen6309** [comment]
Hi, I did not get error when training the network,
"tile_indeces" is supposed to be defined at line 450 in the soft_ncut.py

could you first run "python soft_ncut.py",
this should check all the function in soft_ncut.py, 
we can then further check if there's other bug.

Please let me know if there's further information, thx

**Comment by kos95** [comment]
It maybe a different problem, but when I ran "python soft_ncut.py", it showed below failures.
What might be the reason? @lwchen6309 

max error of image_weights = 7.6449e-01
F2019-05-21 19:35:51.383642: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
max error of soft_ncut = 6.7681e-01
F.
======================================================================
FAIL: test_image_weight (__main__.TestBrightWeight)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "soft_ncut.py", line 672, in test_image_weight
    np.testing.assert_allclose(sparse_bright_weight, dense_bright_weight, rtol=1e-6, atol=1e-6)
  File "/home/me/anaconda3/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1493, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/me/anaconda3/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=1e-06

Mismatch: 43.2%
Max absolute difference: 0.76448863
Max relative difference: nan
 x: array([[[1.      , 0.939413, 0.7788  , ..., 0.      , 0.      ,
         0.      ],
        [0.939413, 1.      , 0.939413, ..., 0.      , 0.      ,...
 y: array([[[1.      , 0.930066, 0.748264, ..., 0.      , 0.      ,
         0.      ],
        [0.930066, 1.      , 0.930066, ..., 0.      , 0.      ,...

======================================================================
FAIL: test_soft_ncut (__main__.TestBrightWeight)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "soft_ncut.py", line 693, in test_soft_ncut
    np.testing.assert_allclose(sp_soft_ncut, dn_soft_ncut, rtol=1e-4, atol=1e-6)
  File "/home/me/anaconda3/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1493, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/me/anaconda3/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=1e-06

Mismatch: 100%
Max absolute difference: 0.67681287
Max relative difference: 0.059044
 x: array([12.139668], dtype=float32)
 y: array([11.462856])

----------------------------------------------------------------------
Ran 3 tests in 0.982s

FAILED (failures=2)
