### ISSUE TITLE
WNet Batch initialization Error

### ISSUE THREAD

**Issue by al3ks1s** [lwchen6309/unsupervised-image-segmentation-by-WNet-with-NormalizedCut#5]
Hello, 

I have tried using the wnet code but each time i try to train it, it says :

Initializing Batch Dataset Reader...                                                                                                                      Traceback (most recent call last):                                                                                                                          

File "src\UNet.py", line 355, in <module>                                                                                                                   train_dataset_reader, validation_dataset_reader = create_BatchDatset()                                                                                  

File "D:\alex\Documents\Workspace py\seg\unsupervised-image-segmentation-by-WNet-with-NormalizedCut-master\src\data_io\BatchDatsetReader_VOC.py", line 109, in create_BatchDatset                                                                                                                                     train_dataset = BatchDatset(data_record['training'], 

File "D:\alex\Documents\Workspace py\seg\unsupervised-image-segmentation-by-WNet-with-NormalizedCut-master\src\data_io\BatchDatsetReader_VOC.py", line 127, in __init__                                                                                                                                               self.read_data_to_self(data_records)         

File "D:\alex\Documents\Workspace py\seg\unsupervised-image-segmentation-by-WNet-with-NormalizedCut-master\src\data_io\BatchDatsetReader_VOC.py", line 135, in read_data_to_self                                                                                                                                      [resize_size, resize_size], interp='bilinear') for datum in data_records])                    

File "D:\Programmes\Anaconda\lib\site-packages\numpy\core\shape_base.py", line 349, in stack                                                                raise ValueError('need at least one array to stack')                                                                                                  ValueError: need at least one array to stack

**Comment by robertkirsten** [comment]
Hi,

I have the same problem, were you able to resolve it @al3ks1s?
If you were could you please share how you managed to?
Do you have any thoughts on this problem @lwchen6309?

Thx in advance

**Comment by al3ks1s** [comment]
Hello, 

If i were t guess, i would say that you're on windows, in my case, the os.path.join putted "\" in pathfiles and it didn't worked because of that, i just used filepath.replace("\\", "/") exery time i see the os path join.

It worked then.

**Comment by robertkirsten** [comment]
First of all thank you for your help!
Unfortunately your tip hasn't solved my issue.
Can you specify which command line options you used to run the program and which file you executed?

Thanks

**Comment by al3ks1s** [comment]
I just used the normal options, also, it is a double backslash on the replace, github removed the second one

**Comment by robertkirsten** [comment]
I used the double backslash, however it hasn't worked.
I used "python WNet_naive.py --mode train --num_layers 9 --debug True" 
Did you run the WNet_bright.py file?

**Comment by azacha** [comment]
@robertkirsten 
The blackslash solution works fine. If think your issue is due to the fact, that you created a empty pickle file while running the code the first time.
If you delete the pickle file, it should work.
